name = "agentflow-worker"
main = "worker/src/index.ts"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
name = "agentflow-worker"

[[durable_objects.bindings]]
name = "WORKFLOW_AGENT"
class_name = "WorkflowAgent"

[[durable_objects.bindings]]
name = "LLM_AGENT"
class_name = "LLMAgent"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WorkflowAgent", "LLMAgent"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "WORKFLOWS_KV"
id = "your-kv-namespace-id"

[vars]
ENVIRONMENT = "development"
